// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "fiber@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/adoptions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene una lista paginada de todas las adopciones.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adoptions"
                ],
                "summary": "Lista todas las adopciones",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset para paginación",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Límite de resultados por página",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponsePag-response_AdoptionResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Crea una nueva adopción en la aplicación.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adoptions"
                ],
                "summary": "Crea una nueva adopción",
                "parameters": [
                    {
                        "description": "Solicitud de adopción",
                        "name": "adoptionRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AdoptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_AdoptionResponse"
                        }
                    }
                }
            }
        },
        "/adoptions/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene los detalles de una adopción según su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adoptions"
                ],
                "summary": "Obtiene una adopción por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la adopción",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_AdoptionResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina una adopcion identificada por su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adoptions"
                ],
                "summary": "Elimina una adopcion programada",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Adoption id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_AdoptionResponse"
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene una lista paginada de todos los eventos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Lista todos los eventos",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset para paginación",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Límite de resultados por página",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponsePag-array_response_EventResponse"
                        }
                    }
                }
            }
        },
        "/events/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene los detalles de un Evento según su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Obtiene un Evento por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Evento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_EventResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina un Evento identificado por su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Elimina un Evento programado",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Evento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_EventResponse"
                        }
                    }
                }
            }
        },
        "/pets": {
            "get": {
                "description": "Lista todas las mascotas de la aplicación.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "Lista a todas las mascotas",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset de paginación",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Límite de resultados por página",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filtrar mascota por raza",
                        "name": "breed",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filtrar mascota por color",
                        "name": "color",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponsePag-response_PetResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Crea una nueva mascota en la aplicación.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "Crea una nueva mascota",
                "parameters": [
                    {
                        "description": "Pet request payload",
                        "name": "petRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_PetResponse"
                        }
                    }
                }
            }
        },
        "/pets/{id}": {
            "get": {
                "description": "Muestra una mascota con el id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "Mostrar a una mascota",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pet id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_PetResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina una mascota identificada por su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "Elimina una mascota",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pet id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_PetResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza los detalles de una mascota identificada por su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "Actualiza los detalles de una mascota",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pet id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Pet update request payload",
                        "name": "updatePetRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdatePetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_PetResponse"
                        }
                    }
                }
            }
        },
        "/pets/{id}/img": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza las imágenes de una mascota identificada por su ID.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "Actualiza las imágenes de una mascota",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pet id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Imagen 1 de la mascota",
                        "name": "img_1",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Imagen 2 de la mascota",
                        "name": "img_2",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Imagen 3 de la mascota",
                        "name": "img_3",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Imagen 4 de la mascota",
                        "name": "img_4",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Imagen 5 de la mascota",
                        "name": "img_5",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_PetResponse"
                        }
                    }
                }
            }
        },
        "/reports": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene una lista paginada de todos los informes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Lista todos los informes",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset para paginación",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Límite de resultados por página",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponsePag-response_ReportResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Crea un nuevo informe en la aplicación.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Crea un nuevo informe",
                "parameters": [
                    {
                        "description": "Solicitud de informe",
                        "name": "reportRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ReportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_ReportResponse"
                        }
                    }
                }
            }
        },
        "/reports/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene los detalles de un informe según su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Obtiene un informe por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del informe",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_ReportResponse"
                        }
                    }
                }
            }
        },
        "/roles": {
            "get": {
                "description": "Obtiene todos los roles.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles"
                ],
                "summary": "Lista todos los roles",
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-array_response_RoleResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Lista todos los usuarios de la aplicación.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Lista todos los usuarios",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset de paginación",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Límite de resultados por página",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponsePag-response_UserResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina un usuario identificada por su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Elimina un usuario",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_UserResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza los detalles de usuario identificado por su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Actualiza los detalles de usuario",
                "parameters": [
                    {
                        "description": "Solicitud de actualización de usuario",
                        "name": "updateUserRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_UserResponse"
                        }
                    }
                }
            }
        },
        "/users/img": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza la imagen de usuario identificado por su ID.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Actualiza la imagen de usuario",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Imagen de usuario",
                        "name": "user_img",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_UserResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "Inicia sesión de usuario con credenciales proporcionadas.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Inicia sesión de usuario",
                "parameters": [
                    {
                        "description": "Solicitud de inicio de sesión",
                        "name": "loginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_LoginResponse"
                        }
                    }
                }
            }
        },
        "/users/recover": {
            "post": {
                "description": "Envía un correo electrónico con una nueva contraseña generada.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Recupera la contraseña de usuario",
                "parameters": [
                    {
                        "description": "Solicitud de restablecimiento de contraseña",
                        "name": "passwordResetRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PasswordResetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_UserResponse"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "Crea un nuevo usuario en la aplicación.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Crea un nuevo usuario",
                "parameters": [
                    {
                        "description": "Solicitud de creación de usuario",
                        "name": "userRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_UserResponse"
                        }
                    }
                }
            }
        },
        "/users/self": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Muestra un usuario propio que esta logeado actualmente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Muestra al mismo usuario que hizo la peticion",
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_UserResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Muestra un usuario con el ID especificado.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Muestra un usuario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del usuario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_UserResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina un usuario identificada por su ID. Solo los de un rol superior pueden utilizar este endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Elimina un usuario desde otro usuario con un rol superior",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_UserResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza los detalles de usuario identificado por su ID. Solo los de un rol superior pueden utilizar esta endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Actualiza los detalles de usuario desde otro usuario con un rol superior",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del usuario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Solicitud de actualización de usuario",
                        "name": "updateUserRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_UserResponse"
                        }
                    }
                }
            }
        },
        "/visits": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene una lista paginada de todas las visitas.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visits"
                ],
                "summary": "Lista todas las visitas",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset para paginación",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Límite de resultados por página",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponsePag-response_VisitResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Crea una nueva visita en la aplicación.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visits"
                ],
                "summary": "Crea una nueva visita",
                "parameters": [
                    {
                        "description": "Solicitud de visita",
                        "name": "visitRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.VisitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_VisitResponse"
                        }
                    }
                }
            }
        },
        "/visits/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene los detalles de una visita según su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visits"
                ],
                "summary": "Obtiene una visita por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la visita",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_VisitResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina una visita identificada por su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visits"
                ],
                "summary": "Elimina una visita programada",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Visit id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_VisitResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.Pagination": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "has_next_page": {
                    "type": "boolean"
                },
                "has_prev_page": {
                    "type": "boolean"
                },
                "items_per_page": {
                    "type": "integer"
                },
                "total_items": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "request.AdoptionRequest": {
            "type": "object",
            "required": [
                "comment",
                "date",
                "pet_id"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "integer"
                }
            }
        },
        "request.LoginRequest": {
            "type": "object",
            "required": [
                "identity",
                "password",
                "role_id"
            ],
            "properties": {
                "identity": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer"
                }
            }
        },
        "request.PasswordResetRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "request.PetRequest": {
            "type": "object",
            "required": [
                "born_date",
                "breed",
                "color",
                "height",
                "location",
                "name",
                "pet_type_id",
                "weight"
            ],
            "properties": {
                "born_date": {
                    "type": "string"
                },
                "breed": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "height": {
                    "type": "number"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pet_type_id": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "request.ReportRequest": {
            "type": "object",
            "required": [
                "description",
                "reported_user_id",
                "reporter_user_id"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "reported_user_id": {
                    "type": "integer"
                },
                "reporter_user_id": {
                    "type": "integer"
                }
            }
        },
        "request.UpdatePetRequest": {
            "type": "object",
            "properties": {
                "adopted": {
                    "type": "boolean"
                },
                "born_date": {
                    "type": "string"
                },
                "breed": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "height": {
                    "type": "number"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pet_type_id": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "request.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "dni": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "request.UserRequest": {
            "type": "object",
            "required": [
                "dni",
                "email",
                "last_name",
                "name",
                "password",
                "phone_number",
                "role_id"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "dni": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "request.VisitRequest": {
            "type": "object",
            "required": [
                "date",
                "pet_id"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "integer"
                }
            }
        },
        "response.AdoptionResponse": {
            "type": "object",
            "properties": {
                "adoption_date": {
                    "type": "string"
                },
                "application_date": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "pet": {
                    "$ref": "#/definitions/response.PetResponse"
                },
                "user": {
                    "$ref": "#/definitions/response.UserResponse"
                }
            }
        },
        "response.BaseResponse-array_response_RoleResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resource": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.RoleResponse"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BaseResponse-response_AdoptionResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resource": {
                    "$ref": "#/definitions/response.AdoptionResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BaseResponse-response_EventResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resource": {
                    "$ref": "#/definitions/response.EventResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BaseResponse-response_LoginResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resource": {
                    "$ref": "#/definitions/response.LoginResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BaseResponse-response_PetResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resource": {
                    "$ref": "#/definitions/response.PetResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BaseResponse-response_ReportResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resource": {
                    "$ref": "#/definitions/response.ReportResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BaseResponse-response_UserResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resource": {
                    "$ref": "#/definitions/response.UserResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BaseResponse-response_VisitResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resource": {
                    "$ref": "#/definitions/response.VisitResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BaseResponsePag-array_response_EventResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/common.Pagination"
                },
                "resource": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.EventResponse"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BaseResponsePag-response_AdoptionResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/common.Pagination"
                },
                "resource": {
                    "$ref": "#/definitions/response.AdoptionResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BaseResponsePag-response_PetResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/common.Pagination"
                },
                "resource": {
                    "$ref": "#/definitions/response.PetResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BaseResponsePag-response_ReportResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/common.Pagination"
                },
                "resource": {
                    "$ref": "#/definitions/response.ReportResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BaseResponsePag-response_UserResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/common.Pagination"
                },
                "resource": {
                    "$ref": "#/definitions/response.UserResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.BaseResponsePag-response_VisitResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/common.Pagination"
                },
                "resource": {
                    "$ref": "#/definitions/response.VisitResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.EventResponse": {
            "type": "object",
            "properties": {
                "allowVolunteers": {
                    "type": "boolean"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imageUrl": {
                    "type": "string"
                },
                "ong": {
                    "$ref": "#/definitions/response.UserResponse"
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.UserResponse"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "response.LoginResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "exp": {
                    "type": "string"
                },
                "iat": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "response.PetResponse": {
            "type": "object",
            "properties": {
                "adppted": {
                    "type": "boolean"
                },
                "age": {
                    "type": "integer"
                },
                "breed": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "height": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pet_type": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/response.UserResponse"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "response.ReportResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "report_date": {
                    "type": "string"
                },
                "reported_user": {
                    "$ref": "#/definitions/response.UserResponse"
                },
                "reporter": {
                    "$ref": "#/definitions/response.UserResponse"
                }
            }
        },
        "response.RoleResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "response.UserResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "dni": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PetResponse"
                    }
                },
                "phone_number": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "response.VisitResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "pet": {
                    "$ref": "#/definitions/response.PetResponse"
                },
                "user": {
                    "$ref": "#/definitions/response.UserResponse"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Enter Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "HairyPets API",
	Description:      "This is a HairyPets API swagger",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
